"""
Engine 9 — Document Output Engine
Produces TXT, DOCX, and PDF exports of completed proposals.
"""

from __future__ import annotations

import os
from datetime import datetime
from typing import Any, Dict, List

import tempfile
EXPORT_DIR = os.path.join(tempfile.gettempdir(), "sbir_exports")


AI_DISCLAIMER = (
    "AI-GENERATED CONTENT DISCLAIMER: This document was produced using artificial "
    "intelligence and is provided as a DRAFT ONLY. It may contain errors, omissions, "
    "or inaccuracies. This content MUST be thoroughly reviewed, verified, and approved "
    "by a qualified professional — including a subject-matter expert, grant writer, "
    "compliance officer, or legal advisor — before submission to any funding agency. "
    "AtiFixia is a productivity and drafting tool, not a substitute for professional "
    "judgment. The submitting organization bears sole responsibility for the accuracy, "
    "compliance, and appropriateness of any content submitted under its name."
)


class DocumentOutputEngine:
    """
    Generates submission-ready documents in TXT, DOCX, and PDF formats.
    """

    def __init__(self):
        os.makedirs(EXPORT_DIR, exist_ok=True)

    async def export(
        self,
        proposal: Any,
        sections: List[Any],
        fmt: str,
        include_scoring: bool = True,
        include_reviewer: bool = False,
        include_compliance: bool = True,
    ) -> Dict[str, Any]:
        """Route to format-specific exporter."""
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        safe_title = "".join(c if c.isalnum() or c in "-_" else "_" for c in proposal.title[:40])
        filename = f"{safe_title}_{timestamp}.{fmt}"
        filepath = os.path.join(EXPORT_DIR, filename)

        if fmt == "txt":
            self._export_txt(filepath, proposal, sections)
        elif fmt == "docx":
            self._export_docx(filepath, proposal, sections)
        elif fmt == "pdf":
            self._export_pdf(filepath, proposal, sections)
        else:
            raise ValueError(f"Unsupported format: {fmt}")

        file_size = os.path.getsize(filepath)
        download_url = f"/api/v1/documents/download/{filename}"

        return {
            "download_url": download_url,
            "file_size": file_size,
            "exported_at": datetime.utcnow(),
        }

    # ── TXT ───────────────────────────────────────────────────────────────────

    def _export_txt(self, filepath: str, proposal: Any, sections: List[Any]) -> None:
        import textwrap
        disclaimer_wrapped = "\n".join(textwrap.wrap(AI_DISCLAIMER, width=68))
        lines = [
            "=" * 70,
            proposal.title.upper(),
            f"Agency: {proposal.agency}  |  Phase: {proposal.phase.replace('_', ' ').title()}",
            f"Status: {proposal.status}  |  Version: {proposal.version}",
            "=" * 70,
            "",
            "⚠  " + "─" * 65,
            disclaimer_wrapped,
            "─" * 68,
            "",
        ]
        for section in sections:
            if section.content:
                lines += [
                    f"\n{'─' * 70}",
                    f"  {section.title.upper()}",
                    f"{'─' * 70}",
                    "",
                    section.content,
                    "",
                ]
        lines += [
            "=" * 70,
            f"Generated by AtiFixia SBIR Intelligence Platform™",
            f"Exported: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            "=" * 70,
        ]

        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

    # ── DOCX ──────────────────────────────────────────────────────────────────

    def _export_docx(self, filepath: str, proposal: Any, sections: List[Any]) -> None:
        try:
            from docx import Document
            from docx.shared import Inches, Pt, RGBColor
            from docx.enum.text import WD_ALIGN_PARAGRAPH

            doc = Document()

            # Page margins
            for section in doc.sections:
                section.top_margin    = Inches(1)
                section.bottom_margin = Inches(1)
                section.left_margin   = Inches(1.25)
                section.right_margin  = Inches(1.25)

            # Title
            title_para = doc.add_paragraph()
            title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = title_para.add_run(proposal.title)
            run.bold = True
            run.font.size = Pt(16)

            # Metadata line
            meta = doc.add_paragraph()
            meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
            meta.add_run(
                f"Agency: {proposal.agency}  |  Phase: {proposal.phase.replace('_', ' ').title()}  "
                f"|  Version: {proposal.version}"
            ).font.size = Pt(10)

            doc.add_paragraph()

            # ── AI Disclaimer box ─────────────────────────────────────────────
            from docx.oxml.ns import qn
            from docx.oxml import OxmlElement
            disclaimer_para = doc.add_paragraph()
            disclaimer_run = disclaimer_para.add_run("⚠  AI-GENERATED CONTENT DISCLAIMER\n")
            disclaimer_run.bold = True
            disclaimer_run.font.size = Pt(9)
            disclaimer_run.font.color.rgb = RGBColor(0x92, 0x40, 0x0E)
            body_run = disclaimer_para.add_run(AI_DISCLAIMER)
            body_run.font.size = Pt(9)
            body_run.font.color.rgb = RGBColor(0x44, 0x33, 0x00)
            # Shade background amber
            pPr = disclaimer_para._p.get_or_add_pPr()
            shd = OxmlElement("w:shd")
            shd.set(qn("w:val"), "clear")
            shd.set(qn("w:color"), "auto")
            shd.set(qn("w:fill"), "FFF3CD")
            pPr.append(shd)
            # Border
            pBdr = OxmlElement("w:pBdr")
            for side in ("top", "left", "bottom", "right"):
                bdr = OxmlElement(f"w:{side}")
                bdr.set(qn("w:val"), "single")
                bdr.set(qn("w:sz"), "6")
                bdr.set(qn("w:space"), "4")
                bdr.set(qn("w:color"), "D97706")
                pBdr.append(bdr)
            pPr.append(pBdr)
            doc.add_paragraph()
            # ─────────────────────────────────────────────────────────────────

            # Sections
            for sec in sections:
                if not sec.content:
                    continue
                # Section heading
                heading = doc.add_paragraph(style="Heading 1")
                heading.add_run(sec.title).bold = True

                # Content paragraphs
                for para_text in sec.content.split("\n\n"):
                    para_text = para_text.strip()
                    if para_text:
                        doc.add_paragraph(para_text)

                doc.add_paragraph()

            # Footer
            footer_para = doc.add_paragraph()
            footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            footer_run = footer_para.add_run(
                f"Generated by AtiFixia SBIR Intelligence Platform™  |  "
                f"{datetime.utcnow().strftime('%Y-%m-%d')}"
            )
            footer_run.font.size = Pt(9)
            footer_run.font.color.rgb = RGBColor(0x80, 0x80, 0x80)

            doc.save(filepath)

        except ImportError:
            # Fallback to TXT if python-docx not installed
            txt_path = filepath.replace(".docx", ".txt")
            self._export_txt(txt_path, proposal, sections)
            import shutil
            shutil.copy(txt_path, filepath)

    # ── PDF ───────────────────────────────────────────────────────────────────

    def _export_pdf(self, filepath: str, proposal: Any, sections: List[Any]) -> None:
        try:
            from reportlab.lib.pagesizes import LETTER
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.platypus import (
                SimpleDocTemplate, Paragraph, Spacer, HRFlowable
            )
            from reportlab.lib import colors

            doc_obj = SimpleDocTemplate(
                filepath,
                pagesize=LETTER,
                rightMargin=1.25 * inch,
                leftMargin=1.25 * inch,
                topMargin=1 * inch,
                bottomMargin=1 * inch,
            )

            styles = getSampleStyleSheet()
            title_style = ParagraphStyle(
                "TitleStyle", parent=styles["Title"],
                fontSize=16, spaceAfter=6, textColor=colors.HexColor("#1a3a6b"),
            )
            heading_style = ParagraphStyle(
                "HeadingStyle", parent=styles["Heading1"],
                fontSize=12, spaceBefore=12, spaceAfter=4,
                textColor=colors.HexColor("#1a3a6b"),
            )
            body_style = ParagraphStyle(
                "BodyStyle", parent=styles["Normal"],
                fontSize=10, leading=14, spaceAfter=6,
            )

            disclaimer_style = ParagraphStyle(
                "DisclaimerStyle", parent=styles["Normal"],
                fontSize=8.5, leading=12, spaceAfter=6,
                backColor=colors.HexColor("#FFF3CD"),
                borderColor=colors.HexColor("#D97706"),
                borderWidth=1, borderPadding=8,
                textColor=colors.HexColor("#443300"),
            )
            disclaimer_label_style = ParagraphStyle(
                "DisclaimerLabel", parent=disclaimer_style,
                fontName="Helvetica-Bold",
                textColor=colors.HexColor("#92400E"),
            )

            story = [
                Paragraph(proposal.title, title_style),
                Paragraph(
                    f"Agency: {proposal.agency}  |  Phase: {proposal.phase.replace('_', ' ').title()}",
                    styles["Normal"],
                ),
                Spacer(1, 0.2 * inch),
                HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a3a6b")),
                Spacer(1, 0.1 * inch),
                Paragraph("⚠  AI-GENERATED CONTENT DISCLAIMER", disclaimer_label_style),
                Paragraph(AI_DISCLAIMER.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"), disclaimer_style),
                Spacer(1, 0.15 * inch),
            ]

            for sec in sections:
                if not sec.content:
                    continue
                story.append(Paragraph(sec.title, heading_style))
                for para_text in sec.content.split("\n\n"):
                    para_text = para_text.strip()
                    if para_text:
                        # Escape HTML special chars
                        safe = para_text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                        story.append(Paragraph(safe, body_style))
                story.append(Spacer(1, 0.15 * inch))

            story += [
                HRFlowable(width="100%", thickness=0.5, color=colors.grey),
                Spacer(1, 0.05 * inch),
                Paragraph(
                    f"<i>Generated by AtiFixia SBIR Intelligence Platform™  |  "
                    f"{datetime.utcnow().strftime('%Y-%m-%d')}</i>",
                    styles["Normal"],
                ),
            ]

            doc_obj.build(story)

        except ImportError:
            # Fallback to TXT
            self._export_txt(filepath.replace(".pdf", ".txt"), proposal, sections)
