"""
Engine 9 — Document Output Engine
Produces TXT, DOCX, and PDF exports of completed proposals.
"""

from __future__ import annotations

import os
from datetime import datetime
from typing import Any, Dict, List

import tempfile
EXPORT_DIR = os.path.join(tempfile.gettempdir(), "sbir_exports")


AI_DISCLAIMER = (
    "AI-GENERATED CONTENT DISCLAIMER: This document was produced using artificial "
    "intelligence and is provided as a DRAFT ONLY. It may contain errors, omissions, "
    "or inaccuracies. This content MUST be thoroughly reviewed, verified, and approved "
    "by a qualified professional — including a subject-matter expert, grant writer, "
    "compliance officer, or legal advisor — before submission to any funding agency. "
    "Clariva is a productivity and drafting tool, not a substitute for professional "
    "judgment. The submitting organization bears sole responsibility for the accuracy, "
    "compliance, and appropriateness of any content submitted under its name."
)


class DocumentOutputEngine:
    """
    Generates submission-ready documents in TXT, DOCX, and PDF formats.
    """

    def __init__(self):
        os.makedirs(EXPORT_DIR, exist_ok=True)

    async def export(
        self,
        proposal: Any,
        sections: List[Any],
        fmt: str,
        include_scoring: bool = True,
        include_reviewer: bool = False,
        include_compliance: bool = True,
    ) -> Dict[str, Any]:
        """Route to format-specific exporter."""
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        safe_title = "".join(c if c.isalnum() or c in "-_" else "_" for c in proposal.title[:40])
        filename = f"{safe_title}_{timestamp}.{fmt}"
        filepath = os.path.join(EXPORT_DIR, filename)

        if fmt == "txt":
            self._export_txt(filepath, proposal, sections)
        elif fmt == "docx":
            self._export_docx(filepath, proposal, sections)
        elif fmt == "pdf":
            self._export_pdf(filepath, proposal, sections)
        else:
            raise ValueError(f"Unsupported format: {fmt}")

        file_size = os.path.getsize(filepath)
        download_url = f"/api/v1/documents/download/{filename}"

        return {
            "download_url": download_url,
            "file_size": file_size,
            "exported_at": datetime.utcnow(),
        }

    # ── TXT ───────────────────────────────────────────────────────────────────

    def _export_txt(self, filepath: str, proposal: Any, sections: List[Any]) -> None:
        import textwrap
        disclaimer_wrapped = "\n".join(textwrap.wrap(AI_DISCLAIMER, width=68))
        lines = [
            "=" * 70,
            proposal.title.upper(),
            f"Agency: {proposal.agency}  |  Phase: {proposal.phase.replace('_', ' ').title()}",
            f"Status: {proposal.status}  |  Version: {proposal.version}",
            "=" * 70,
            "",
            "⚠  " + "─" * 65,
            disclaimer_wrapped,
            "─" * 68,
            "",
        ]
        for section in sections:
            if section.content:
                lines += [
                    f"\n{'─' * 70}",
                    f"  {section.title.upper()}",
                    f"{'─' * 70}",
                    "",
                    section.content,
                    "",
                ]
        lines += [
            "=" * 70,
            f"Generated by Clariva Intelligent Grant Writing Platform™",
            f"Exported: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            "=" * 70,
        ]

        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

    # ── DOCX ──────────────────────────────────────────────────────────────────

    def _export_docx(self, filepath: str, proposal: Any, sections: List[Any]) -> None:
        try:
            from docx import Document
            from docx.shared import Pt, RGBColor
            from docx.oxml.ns import qn
            from docx.oxml import OxmlElement
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            from utils.doc_utils import (
                apply_federal_margins, add_federal_heading, add_body_para,
                add_page_numbers, render_content, _make_run, _para_spacing,
                FEDERAL_FONT, H1_PT,
            )

            doc = Document()
            apply_federal_margins(doc)

            # ── Title ─────────────────────────────────────────────────────────
            title_para = doc.add_paragraph()
            title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            _para_spacing(title_para, after=4, before=0)
            _make_run(title_para, proposal.title, bold=True, pt=H1_PT)

            # Metadata line
            meta = doc.add_paragraph()
            meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
            _para_spacing(meta, after=6)
            _make_run(meta,
                      f"Agency: {proposal.agency}  |  "
                      f"Phase: {proposal.phase.replace('_', ' ').title()}  |  "
                      f"Version: {proposal.version}",
                      pt=10)

            # ── AI Disclaimer box ─────────────────────────────────────────────
            disclaimer_para = doc.add_paragraph()
            _para_spacing(disclaimer_para, after=8)
            dr = disclaimer_para.add_run("AI-GENERATED DRAFT — REQUIRES PROFESSIONAL REVIEW\n")
            dr.bold = True; dr.font.size = Pt(9)
            dr.font.color.rgb = RGBColor(0x92, 0x40, 0x0E)
            br = disclaimer_para.add_run(AI_DISCLAIMER)
            br.font.size = Pt(9)
            br.font.color.rgb = RGBColor(0x44, 0x33, 0x00)
            pPr = disclaimer_para._p.get_or_add_pPr()
            shd = OxmlElement("w:shd")
            shd.set(qn("w:val"), "clear"); shd.set(qn("w:color"), "auto")
            shd.set(qn("w:fill"), "FFF3CD")
            pPr.append(shd)
            pBdr = OxmlElement("w:pBdr")
            for side in ("top", "left", "bottom", "right"):
                bdr = OxmlElement(f"w:{side}")
                bdr.set(qn("w:val"), "single"); bdr.set(qn("w:sz"), "6")
                bdr.set(qn("w:space"), "4"); bdr.set(qn("w:color"), "D97706")
                pBdr.append(bdr)
            pPr.append(pBdr)
            # ─────────────────────────────────────────────────────────────────

            # ── Sections ──────────────────────────────────────────────────────
            for sec in sections:
                if not sec.content:
                    continue
                add_federal_heading(doc, sec.title, level=1)
                render_content(doc, sec.content)

            # ── Page numbers ──────────────────────────────────────────────────
            add_page_numbers(doc)

            doc.save(filepath)

        except ImportError:
            txt_path = filepath.replace(".docx", ".txt")
            self._export_txt(txt_path, proposal, sections)
            import shutil
            shutil.copy(txt_path, filepath)

    # ── PDF ───────────────────────────────────────────────────────────────────

    def _export_pdf(self, filepath: str, proposal: Any, sections: List[Any]) -> None:
        try:
            from reportlab.lib.pagesizes import LETTER
            from reportlab.lib.styles import ParagraphStyle
            from reportlab.lib.units import inch
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
            from reportlab.lib import colors
            from utils.doc_utils import get_pdf_styles, pdf_page_number, strip_for_pdf

            S = get_pdf_styles()
            NAVY = colors.HexColor("#1F4E79")

            disclaimer_style = ParagraphStyle(
                "DisclaimerStyle", fontName="Times-Roman", fontSize=9,
                leading=13, spaceAfter=6,
                backColor=colors.HexColor("#FFF3CD"),
                borderColor=colors.HexColor("#D97706"),
                borderWidth=1, borderPadding=8,
                textColor=colors.HexColor("#443300"),
            )
            disclaimer_label = ParagraphStyle(
                "DisclaimerLabel", fontName="Times-Bold", fontSize=9,
                textColor=colors.HexColor("#92400E"),
                backColor=colors.HexColor("#FFF3CD"),
                borderPadding=8,
            )

            doc_obj = SimpleDocTemplate(
                filepath, pagesize=LETTER,
                leftMargin=inch, rightMargin=inch,
                topMargin=inch, bottomMargin=inch,
            )

            story = [
                Paragraph(strip_for_pdf(proposal.title), S["title"]),
                Paragraph(
                    f"Agency: {proposal.agency}  |  "
                    f"Phase: {proposal.phase.replace('_', ' ').title()}",
                    S["small"],
                ),
                Spacer(1, 0.15 * inch),
                HRFlowable(width="100%", thickness=1, color=NAVY),
                Spacer(1, 0.08 * inch),
                Paragraph("AI-GENERATED DRAFT — REQUIRES PROFESSIONAL REVIEW", disclaimer_label),
                Paragraph(
                    AI_DISCLAIMER.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"),
                    disclaimer_style,
                ),
                Spacer(1, 0.15 * inch),
            ]

            for sec in sections:
                if not sec.content:
                    continue
                story.append(Paragraph(strip_for_pdf(sec.title), S["h1"]))
                for para_text in sec.content.split("\n\n"):
                    para_text = para_text.strip()
                    if not para_text:
                        continue
                    import re
                    if re.match(r'^#{1,3}\s', para_text) or re.match(r'^[A-Z]\.\s', para_text):
                        story.append(Paragraph(strip_for_pdf(para_text), S["h2"]))
                    else:
                        story.append(Paragraph(strip_for_pdf(para_text), S["body"]))
                story.append(Spacer(1, 0.12 * inch))

            story += [
                HRFlowable(width="100%", thickness=0.5, color=colors.grey),
                Spacer(1, 0.05 * inch),
                Paragraph(
                    f"<i>Generated by Clariva SBIR Intelligence Platform  |  "
                    f"{datetime.utcnow().strftime('%Y-%m-%d')}</i>",
                    S["small"],
                ),
            ]

            doc_obj.build(story,
                          onFirstPage=pdf_page_number,
                          onLaterPages=pdf_page_number)

        except ImportError:
            self._export_txt(filepath.replace(".pdf", ".txt"), proposal, sections)
