"""
Image generation engine — produces figures for grant proposals.

Dispatch logic:
  FLOW | Step1 → Step2 → Step3 | description  →  matplotlib flowchart (no API cost)
  IMAGE | detailed visual description           →  DALL-E 3 image
  Legacy captions with 'flow'/'process'         →  matplotlib flowchart
  All other legacy captions                     →  DALL-E 3 image
"""

from __future__ import annotations

import io
import re
import logging
from typing import Optional, Tuple, List

_log = logging.getLogger(__name__)


# ── Marker parser ─────────────────────────────────────────────────────────────

def _parse_marker(caption: str) -> Tuple[str, List[str], str]:
    """
    Parse a figure caption into (type, steps, description).

    Structured format (generated by updated _visual_guidance):
      'FLOW | Research → Fabrication → Testing | End-to-end workflow'
      'IMAGE | Cross-sectional schematic of the multi-layer adaptive stack'

    Legacy format (older proposals):
      'Process Flow Diagram — describe the end-to-end technical workflow'
      'Schematic of Adaptive Uniform Components'
    """
    # Structured format: two or more pipe-delimited segments
    parts = [p.strip() for p in caption.split("|")]
    if len(parts) >= 2:
        tag = parts[0].upper()
        if tag.startswith("FLOW"):
            steps = [s.strip() for s in parts[1].split("→") if s.strip()]
            # Also split on commas or semicolons if no arrows
            if not steps or len(steps) < 2:
                steps = [s.strip() for s in re.split(r"[,;]", parts[1]) if s.strip()]
            desc = parts[2].strip() if len(parts) > 2 else parts[1].strip()
            return "flow", steps, desc
        if tag.startswith("IMAGE"):
            return "image", [], parts[1].strip()

    # Legacy: detect by keyword
    cap_lower = caption.lower()
    if any(kw in cap_lower for kw in ("flow diagram", "process flow", "workflow", "flowchart", "flow chart")):
        return "flow", [], caption
    return "image", [], caption


# ── Flowchart (matplotlib) ────────────────────────────────────────────────────

def generate_flowchart(steps: List[str], title: str = "") -> bytes:
    """
    Render a clean horizontal step-by-step flowchart.
    Returns PNG bytes (150 dpi, white background).
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import FancyBboxPatch

    # Sensible defaults when no steps are embedded in the marker
    if not steps or len(steps) < 2:
        steps = [
            "Research & Design",
            "Prototype Development",
            "Testing & Validation",
            "Deployment",
        ]

    # Clamp to 6 steps; trim each label
    steps = [s[:28] for s in steps[:6]]
    n = len(steps)

    NAVY   = "#1F4E79"
    BLUE   = "#2E75B6"
    WHITE  = "#FFFFFF"
    SHADOW = "#CBD5E1"
    PALETTES = [NAVY, BLUE] * 4  # alternating

    fig_w = max(9.0, n * 2.5)
    fig_h = 3.4
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    ax.set_xlim(0, fig_w)
    ax.set_ylim(0, fig_h)
    ax.axis("off")
    ax.set_facecolor("white")
    fig.patch.set_facecolor("white")

    BOX_W = 2.0
    BOX_H = 1.3
    Y_MID = 1.9
    GAP   = 0.45  # gap between boxes
    step_span = fig_w - 0.6  # total horizontal span
    x_gap = (step_span - BOX_W) / max(n - 1, 1)
    X0 = 0.3

    for i, step in enumerate(steps):
        x = X0 + i * x_gap

        # Shadow
        ax.add_patch(FancyBboxPatch(
            (x + 0.05, Y_MID - BOX_H / 2 - 0.05), BOX_W, BOX_H,
            boxstyle="round,pad=0.07", linewidth=0,
            facecolor=SHADOW, zorder=2,
        ))
        # Box
        ax.add_patch(FancyBboxPatch(
            (x, Y_MID - BOX_H / 2), BOX_W, BOX_H,
            boxstyle="round,pad=0.07",
            linewidth=1.5, edgecolor=NAVY,
            facecolor=PALETTES[i], zorder=3,
        ))
        # Step number badge
        badge = plt.Circle((x + 0.27, Y_MID + 0.35), 0.20, color=WHITE, zorder=4)
        ax.add_patch(badge)
        ax.text(x + 0.27, Y_MID + 0.35, str(i + 1),
                ha="center", va="center",
                color=PALETTES[i], fontsize=8.5, fontweight="bold", zorder=5)

        # Label — word-wrap to ~16 chars per line
        words = step.split()
        lines, cur = [], []
        for w in words:
            test = " ".join(cur + [w])
            if len(test) > 16 and cur:
                lines.append(" ".join(cur))
                cur = [w]
            else:
                cur.append(w)
        if cur:
            lines.append(" ".join(cur))
        label = "\n".join(lines[:3])

        ax.text(x + BOX_W / 2, Y_MID - 0.10, label,
                ha="center", va="center",
                color=WHITE, fontsize=7.5, fontweight="bold",
                multialignment="center", zorder=4)

        # Arrow to next box
        if i < n - 1:
            ax.annotate(
                "",
                xy=(x + x_gap + 0.03, Y_MID),
                xytext=(x + BOX_W + 0.04, Y_MID),
                arrowprops=dict(arrowstyle="->", color=NAVY, lw=2.0, mutation_scale=20),
                zorder=6,
            )

    if title:
        fig.text(0.5, 0.03, title[:90], ha="center", va="bottom",
                 fontsize=8.5, color=NAVY, style="italic")

    buf = io.BytesIO()
    plt.savefig(buf, format="png", dpi=150, bbox_inches="tight",
                facecolor="white", edgecolor="none")
    plt.close(fig)
    buf.seek(0)
    return buf.read()


# ── Schematic / architecture diagram (matplotlib) ────────────────────────────

def generate_schematic(description: str) -> bytes:
    """
    Generate a layered system architecture diagram from the figure description.
    Parses comma/semicolon-separated component names from the description text
    and renders them as stacked labelled layers (bottom → top).
    Returns PNG bytes.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import FancyBboxPatch

    # ── Extract components ────────────────────────────────────────────────
    # Look for a list after "showing", "including", "depicting", "comprising", etc.
    comp_match = re.search(
        r'(?:showing|including|depicting|comprising|integrat\w+|with)\s+(.*?)\.?\s*$',
        description, re.IGNORECASE,
    )
    components: List[str] = []
    if comp_match:
        raw = comp_match.group(1)
        parts = re.split(r',|;|\band\b', raw)
        components = [p.strip().title() for p in parts if p.strip() and len(p.strip()) > 2]
        components = [c[:38] for c in components[:6]]

    # Fallback generic if parsing failed
    if len(components) < 2:
        components = [
            "System Input / Sensors",
            "Core Processing Layer",
            "Integration & Control Module",
            "System Output / Actuation",
        ]

    NAVY   = "#1F4E79"
    LAYER_COLORS = ["#1F4E79", "#2E75B6", "#4472C4", "#5B9BD5", "#2E75B6", "#1F4E79"]
    WHITE  = "#FFFFFF"

    n = len(components)
    fig_h = max(4.5, n * 1.05 + 1.8)
    fig, ax = plt.subplots(figsize=(8.5, fig_h))
    ax.set_xlim(0, 8.5)
    ax.set_ylim(0, fig_h)
    ax.axis("off")
    ax.set_facecolor("white")
    fig.patch.set_facecolor("white")

    LAYER_H = 0.75
    LAYER_W = 6.0
    X0 = (8.5 - LAYER_W) / 2
    Y_GAP = 0.22
    y_total = n * (LAYER_H + Y_GAP) - Y_GAP
    Y0 = (fig_h - y_total) / 2 - 0.3

    # Draw layers bottom-up (index 0 = bottom)
    for i, comp in enumerate(components):
        y = Y0 + i * (LAYER_H + Y_GAP)
        color = LAYER_COLORS[i % len(LAYER_COLORS)]

        # Shadow
        ax.add_patch(FancyBboxPatch(
            (X0 + 0.05, y - 0.05), LAYER_W, LAYER_H,
            boxstyle="round,pad=0.06", linewidth=0,
            facecolor="#CBD5E1", zorder=2,
        ))
        # Layer box
        ax.add_patch(FancyBboxPatch(
            (X0, y), LAYER_W, LAYER_H,
            boxstyle="round,pad=0.06",
            linewidth=1.5, edgecolor=NAVY,
            facecolor=color, zorder=3,
        ))
        # Layer number badge
        badge = plt.Circle((X0 + 0.30, y + LAYER_H / 2), 0.20, color=WHITE, zorder=4)
        ax.add_patch(badge)
        ax.text(X0 + 0.30, y + LAYER_H / 2, str(i + 1),
                ha="center", va="center",
                color=color, fontsize=8, fontweight="bold", zorder=5)
        # Label
        ax.text(X0 + LAYER_W / 2, y + LAYER_H / 2, comp,
                ha="center", va="center",
                color=WHITE, fontsize=8.5, fontweight="bold", zorder=4)

        # Upward arrow between layers
        if i < n - 1:
            ax.annotate(
                "",
                xy=(X0 + LAYER_W / 2, y + LAYER_H + Y_GAP - 0.02),
                xytext=(X0 + LAYER_W / 2, y + LAYER_H + 0.02),
                arrowprops=dict(arrowstyle="->", color=NAVY, lw=1.8, mutation_scale=16),
                zorder=6,
            )

    # "Layer 1 (Base)" annotation
    ax.text(X0 - 0.15, Y0 + LAYER_H / 2, "Base\nLayer",
            ha="right", va="center", fontsize=7, color="#888888",
            rotation=90, style="italic")
    ax.text(X0 - 0.15, Y0 + y_total - LAYER_H / 2, "Top\nLayer",
            ha="right", va="center", fontsize=7, color="#888888",
            rotation=90, style="italic")

    # Title
    title_text = re.sub(r'^(FLOW|IMAGE)\s*\|[^|]*\|\s*', '', description, flags=re.IGNORECASE).strip()
    if not title_text:
        title_text = description[:65]
    fig.text(0.5, 0.97, title_text[:80], ha="center", va="top",
             fontsize=8.5, color=NAVY, fontweight="bold", style="italic")

    buf = io.BytesIO()
    plt.savefig(buf, format="png", dpi=150, bbox_inches="tight",
                facecolor="white", edgecolor="none")
    plt.close(fig)
    buf.seek(0)
    return buf.read()


# ── DALL-E 3 image (future / explicit premium tier) ───────────────────────────

async def generate_dalle_image(
    description: str,
    proposal_title: str,
    api_key: str,
) -> Optional[bytes]:
    """
    Call DALL-E 3 to generate a technical illustration.
    Kept for future explicit DALL-E premium tier.
    Returns PNG bytes, or None if the call fails.
    """
    import httpx
    import openai

    desc = re.sub(r'^(FLOW|IMAGE)\s*\|', '', description, flags=re.IGNORECASE).strip()
    desc = desc[:380]

    prompt = (
        "A clean professional technical diagram or scientific illustration "
        f"for a federal grant proposal. Topic: {desc}. "
        "Style: scientific/engineering diagram, white background, navy blue and grey palette. "
        "Formal, precise, no watermarks, no handwriting, landscape orientation."
    )

    try:
        client = openai.AsyncOpenAI(api_key=api_key)
        resp = await client.images.generate(
            model="dall-e-3",
            prompt=prompt,
            size="1792x1024",
            quality="standard",
            n=1,
        )
        url = resp.data[0].url
        async with httpx.AsyncClient(timeout=45) as http:
            r = await http.get(url)
            r.raise_for_status()
            return r.content
    except Exception as exc:
        _log.warning("DALL-E image generation failed: %s", exc)
        return None


# ── Public entry point ────────────────────────────────────────────────────────

async def generate_figure(
    caption: str,
    proposal_title: str,
    api_key: str,
    use_dalle: bool = False,
) -> Optional[bytes]:
    """
    Main entry point.

    FLOW markers  → matplotlib horizontal flowchart (steps extracted from marker).
    IMAGE markers → matplotlib layered architecture diagram (components extracted from caption).
    use_dalle=True → attempt DALL-E 3 for IMAGE type first; falls back to matplotlib.

    Returns PNG bytes, or None on failure (caller falls back to placeholder).
    """
    fig_type, steps, description = _parse_marker(caption)
    _log.info("Figure generation: type=%s steps=%d desc=%.60s", fig_type, len(steps), description)

    if fig_type == "flow":
        try:
            return generate_flowchart(steps, title=description[:80] if description else "")
        except Exception as exc:
            _log.warning("Flowchart generation failed: %s", exc)
            return None
    else:
        # IMAGE type
        if use_dalle:
            img = await generate_dalle_image(description, proposal_title, api_key)
            if img:
                return img
            _log.info("DALL-E failed; falling back to matplotlib schematic")
        try:
            return generate_schematic(description)
        except Exception as exc:
            _log.warning("Schematic generation failed: %s", exc)
            return None
