"""
Image generation engine — produces figures for grant proposals.

Dispatch logic:
  FLOW | Step1 → Step2 → Step3 | description  →  matplotlib flowchart (no API cost)
  IMAGE | detailed visual description           →  DALL-E 3 image
  Legacy captions with 'flow'/'process'         →  matplotlib flowchart
  All other legacy captions                     →  DALL-E 3 image
"""

from __future__ import annotations

import io
import re
import logging
from typing import Optional, Tuple, List

_log = logging.getLogger(__name__)


# ── Marker parser ─────────────────────────────────────────────────────────────

def _parse_marker(caption: str) -> Tuple[str, List[str], str]:
    """
    Parse a figure caption into (type, steps, description).

    Structured format (generated by updated _visual_guidance):
      'FLOW | Research → Fabrication → Testing | End-to-end workflow'
      'IMAGE | Cross-sectional schematic of the multi-layer adaptive stack'

    Legacy format (older proposals):
      'Process Flow Diagram — describe the end-to-end technical workflow'
      'Schematic of Adaptive Uniform Components'
    """
    # Structured format: two or more pipe-delimited segments
    parts = [p.strip() for p in caption.split("|")]
    if len(parts) >= 2:
        tag = parts[0].upper()
        if tag.startswith("FLOW"):
            steps = [s.strip() for s in parts[1].split("→") if s.strip()]
            # Also split on commas or semicolons if no arrows
            if not steps or len(steps) < 2:
                steps = [s.strip() for s in re.split(r"[,;]", parts[1]) if s.strip()]
            desc = parts[2].strip() if len(parts) > 2 else parts[1].strip()
            return "flow", steps, desc
        if tag.startswith("IMAGE"):
            return "image", [], parts[1].strip()

    # Legacy: detect by keyword
    cap_lower = caption.lower()
    if any(kw in cap_lower for kw in ("flow diagram", "process flow", "workflow", "flowchart", "flow chart")):
        return "flow", [], caption
    return "image", [], caption


# ── Flowchart (matplotlib) ────────────────────────────────────────────────────

def generate_flowchart(steps: List[str], title: str = "") -> bytes:
    """
    Render a clean horizontal step-by-step flowchart.
    Returns PNG bytes (150 dpi, white background).
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import FancyBboxPatch

    # Sensible defaults when no steps are embedded in the marker
    if not steps or len(steps) < 2:
        steps = [
            "Research & Design",
            "Prototype Development",
            "Testing & Validation",
            "Deployment",
        ]

    # Clamp to 6 steps; trim each label
    steps = [s[:28] for s in steps[:6]]
    n = len(steps)

    NAVY   = "#1F4E79"
    BLUE   = "#2E75B6"
    WHITE  = "#FFFFFF"
    SHADOW = "#CBD5E1"
    PALETTES = [NAVY, BLUE] * 4  # alternating

    fig_w = max(9.0, n * 2.5)
    fig_h = 3.4
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    ax.set_xlim(0, fig_w)
    ax.set_ylim(0, fig_h)
    ax.axis("off")
    ax.set_facecolor("white")
    fig.patch.set_facecolor("white")

    BOX_W = 2.0
    BOX_H = 1.3
    Y_MID = 1.9
    GAP   = 0.45  # gap between boxes
    step_span = fig_w - 0.6  # total horizontal span
    x_gap = (step_span - BOX_W) / max(n - 1, 1)
    X0 = 0.3

    for i, step in enumerate(steps):
        x = X0 + i * x_gap

        # Shadow
        ax.add_patch(FancyBboxPatch(
            (x + 0.05, Y_MID - BOX_H / 2 - 0.05), BOX_W, BOX_H,
            boxstyle="round,pad=0.07", linewidth=0,
            facecolor=SHADOW, zorder=2,
        ))
        # Box
        ax.add_patch(FancyBboxPatch(
            (x, Y_MID - BOX_H / 2), BOX_W, BOX_H,
            boxstyle="round,pad=0.07",
            linewidth=1.5, edgecolor=NAVY,
            facecolor=PALETTES[i], zorder=3,
        ))
        # Step number badge
        badge = plt.Circle((x + 0.27, Y_MID + 0.35), 0.20, color=WHITE, zorder=4)
        ax.add_patch(badge)
        ax.text(x + 0.27, Y_MID + 0.35, str(i + 1),
                ha="center", va="center",
                color=PALETTES[i], fontsize=8.5, fontweight="bold", zorder=5)

        # Label — word-wrap to ~16 chars per line
        words = step.split()
        lines, cur = [], []
        for w in words:
            test = " ".join(cur + [w])
            if len(test) > 16 and cur:
                lines.append(" ".join(cur))
                cur = [w]
            else:
                cur.append(w)
        if cur:
            lines.append(" ".join(cur))
        label = "\n".join(lines[:3])

        ax.text(x + BOX_W / 2, Y_MID - 0.10, label,
                ha="center", va="center",
                color=WHITE, fontsize=7.5, fontweight="bold",
                multialignment="center", zorder=4)

        # Arrow to next box
        if i < n - 1:
            ax.annotate(
                "",
                xy=(x + x_gap + 0.03, Y_MID),
                xytext=(x + BOX_W + 0.04, Y_MID),
                arrowprops=dict(arrowstyle="->", color=NAVY, lw=2.0, mutation_scale=20),
                zorder=6,
            )

    if title:
        fig.text(0.5, 0.03, title[:90], ha="center", va="bottom",
                 fontsize=8.5, color=NAVY, style="italic")

    buf = io.BytesIO()
    plt.savefig(buf, format="png", dpi=150, bbox_inches="tight",
                facecolor="white", edgecolor="none")
    plt.close(fig)
    buf.seek(0)
    return buf.read()


# ── DALL-E 3 image ────────────────────────────────────────────────────────────

async def generate_dalle_image(
    description: str,
    proposal_title: str,
    api_key: str,
) -> Optional[bytes]:
    """
    Call DALL-E 3 to generate a technical illustration.
    Returns PNG bytes, or None if the call fails.
    """
    import httpx
    import openai

    # Strip any leftover pipe segments
    desc = re.sub(r'^(FLOW|IMAGE)\s*\|', '', description, flags=re.IGNORECASE).strip()
    desc = desc[:380]

    prompt = (
        f"A professional technical diagram or scientific illustration for a U.S. federal "
        f"grant proposal titled '{proposal_title[:80]}'. "
        f"Topic: {desc}. "
        "Style: clean scientific/engineering diagram on plain white background, "
        "suitable for submission to a U.S. government agency. "
        "Navy blue and grey colour palette. Formal, precise, no watermarks, no handwriting. "
        "Landscape orientation."
    )

    try:
        client = openai.AsyncOpenAI(api_key=api_key)
        resp = await client.images.generate(
            model="dall-e-3",
            prompt=prompt,
            size="1792x1024",
            quality="standard",
            n=1,
        )
        url = resp.data[0].url
        async with httpx.AsyncClient(timeout=45) as http:
            r = await http.get(url)
            r.raise_for_status()
            return r.content
    except Exception as exc:
        _log.warning("DALL-E image generation failed: %s", exc)
        return None


# ── Public entry point ────────────────────────────────────────────────────────

async def generate_figure(
    caption: str,
    proposal_title: str,
    api_key: str,
) -> Optional[bytes]:
    """
    Main entry point.  Parse the caption, dispatch to flowchart or DALL-E.
    Returns PNG bytes, or None on failure (caller should fall back to placeholder).
    """
    fig_type, steps, description = _parse_marker(caption)
    _log.info("Figure generation: type=%s steps=%d desc=%.60s", fig_type, len(steps), description)

    if fig_type == "flow":
        try:
            return generate_flowchart(steps, title=description[:80] if description else "")
        except Exception as exc:
            _log.warning("Flowchart generation failed, trying DALL-E: %s", exc)
            return await generate_dalle_image(description or caption, proposal_title, api_key)
    else:
        return await generate_dalle_image(description, proposal_title, api_key)
